/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef communication_CONSTANTS_H
#define communication_CONSTANTS_H

#include "communication_types.h"



class communicationConstants {
 public:
  communicationConstants();

};

extern const communicationConstants g_communication_constants;



#endif
