/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "communication_constants.h"



const communicationConstants g_communication_constants;

communicationConstants::communicationConstants() {
}



