/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ServerByeService_H
#define ServerByeService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "communication_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ServerByeServiceIf {
 public:
  virtual ~ServerByeServiceIf() {}
  virtual void sayBye(const std::string& msg) = 0;
};

class ServerByeServiceIfFactory {
 public:
  typedef ServerByeServiceIf Handler;

  virtual ~ServerByeServiceIfFactory() {}

  virtual ServerByeServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ServerByeServiceIf* /* handler */) = 0;
};

class ServerByeServiceIfSingletonFactory : virtual public ServerByeServiceIfFactory {
 public:
  ServerByeServiceIfSingletonFactory(const ::std::shared_ptr<ServerByeServiceIf>& iface) : iface_(iface) {}
  virtual ~ServerByeServiceIfSingletonFactory() {}

  virtual ServerByeServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ServerByeServiceIf* /* handler */) {}

 protected:
  ::std::shared_ptr<ServerByeServiceIf> iface_;
};

class ServerByeServiceNull : virtual public ServerByeServiceIf {
 public:
  virtual ~ServerByeServiceNull() {}
  void sayBye(const std::string& /* msg */) {
    return;
  }
};

typedef struct _ServerByeService_sayBye_args__isset {
  _ServerByeService_sayBye_args__isset() : msg(false) {}
  bool msg :1;
} _ServerByeService_sayBye_args__isset;

class ServerByeService_sayBye_args {
 public:

  ServerByeService_sayBye_args(const ServerByeService_sayBye_args&);
  ServerByeService_sayBye_args& operator=(const ServerByeService_sayBye_args&);
  ServerByeService_sayBye_args() : msg() {
  }

  virtual ~ServerByeService_sayBye_args() noexcept;
  std::string msg;

  _ServerByeService_sayBye_args__isset __isset;

  void __set_msg(const std::string& val);

  bool operator == (const ServerByeService_sayBye_args & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const ServerByeService_sayBye_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ServerByeService_sayBye_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ServerByeService_sayBye_pargs {
 public:


  virtual ~ServerByeService_sayBye_pargs() noexcept;
  const std::string* msg;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class ServerByeServiceClient : virtual public ServerByeServiceIf {
 public:
  ServerByeServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ServerByeServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sayBye(const std::string& msg);
  void send_sayBye(const std::string& msg);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ServerByeServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<ServerByeServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ServerByeServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_sayBye(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ServerByeServiceProcessor(::std::shared_ptr<ServerByeServiceIf> iface) :
    iface_(iface) {
    processMap_["sayBye"] = &ServerByeServiceProcessor::process_sayBye;
  }

  virtual ~ServerByeServiceProcessor() {}
};

class ServerByeServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ServerByeServiceProcessorFactory(const ::std::shared_ptr< ServerByeServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< ServerByeServiceIfFactory > handlerFactory_;
};

class ServerByeServiceMultiface : virtual public ServerByeServiceIf {
 public:
  ServerByeServiceMultiface(std::vector<std::shared_ptr<ServerByeServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ServerByeServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<ServerByeServiceIf> > ifaces_;
  ServerByeServiceMultiface() {}
  void add(::std::shared_ptr<ServerByeServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void sayBye(const std::string& msg) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->sayBye(msg);
    }
    ifaces_[i]->sayBye(msg);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ServerByeServiceConcurrentClient : virtual public ServerByeServiceIf {
 public:
  ServerByeServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  ServerByeServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sayBye(const std::string& msg);
  void send_sayBye(const std::string& msg);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
