/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef bye_CONSTANTS_H
#define bye_CONSTANTS_H

#include "bye_types.h"



class byeConstants {
 public:
  byeConstants();

};

extern const byeConstants g_bye_constants;



#endif
