// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ClientHelloService.h"
#include "ServerByeService.h"
#include <thread>
#include <iostream>
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TSocket.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace std;
using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class ClientHelloServiceHandler : virtual public ClientHelloServiceIf {
public:
    ClientHelloServiceHandler() {
        // Your initialization goes here
    }

    void sayHello(const std::string& msg) {
        printf("\nserver implement sayHello: %s\n",msg.c_str());
    }
};

static void sendToClient()
{
    Sleep(5000);            //延迟2s时间，等待客户端的服务器先起来
    int port = 8080;
    ::std::shared_ptr<TSocket> socket(new TSocket("localhost", port));
    ::std::shared_ptr<TBufferedTransport> transport(new TBufferedTransport(socket));
    ::std::shared_ptr<TBinaryProtocol> protocol(new TBinaryProtocol(transport));

    ServerByeServiceClient client(protocol);
    try {
        transport->open();

        string msg;
        cout<<"Please input message to send to client: ";
        while(cin>>msg)
        {
            getchar();
            if(msg == "quit")
            {
                return ;
            }
            client.sayBye(msg);
            cout<<"to be continue?(input quit to stop): ";
        }

        transport->close();
    }
    catch (TException& tx) {
        printf("ERROR:%s\n", tx.what());
    }
}

static void handleRecvMsg()
{
    int port = 9090;
    ::std::shared_ptr<ClientHelloServiceHandler> handler(new ClientHelloServiceHandler());
    ::std::shared_ptr<TProcessor> processor(new ClientHelloServiceProcessor(handler));
    ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
    ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
    ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

    TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
    server.serve();
}

int main(int argc, char **argv) {
    printf("---server start---\n");

    thread recvMsgThread(sendToClient);

    handleRecvMsg();
    return 0;
}

