/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef helloBidiService_CONSTANTS_H
#define helloBidiService_CONSTANTS_H

#include "helloBidiService_types.h"



class helloBidiServiceConstants {
 public:
  helloBidiServiceConstants();

};

extern const helloBidiServiceConstants g_helloBidiService_constants;



#endif
